# Dev profile: activated with --spring.profiles.active=dev

# Routing (local map file assumed to be pre-downloaded)
app.routing.local-osm-dir=~/.graphhopper/openstreetmap
app.routing.local-graphhopper-dir=~/.graphhopper/graphhopper
app.routing.osm-file=western-zone-latest.osm.pbf

# Dispatch config
app.dispatch.config.warehouse-code=95001200
app.dispatch.config.order-date=20260920
app.dispatch.config.max-contracted-vehicles=10
app.dispatch.config.max-time-groups=3

# Distance cache persistence (use local file for standalone local development without AWS credentials)
app.routing.cache.persistence-type=file
app.routing.cache.s3-bucket-name=/DevProto/S3/DistanceCache/BucketName
app.routing.cache.ddb-table-name=/DevProto/DDB/DistanceCache/TableName
app.routing.cache.file-path=~/.graphhopper/output.latlongcache

# AWS
aws.profile=route-opt
aws.region=ap-south-1

# Dev Server
server.port=8888

# OptaPlanner
app.solver.solver-config-xml=solver-config.xml

# Logging
logging.level.org.optaplanner=DEBUG
logging.level.dev.aws.proto=DEBUG
